# Generated by Django 5.1.7 on 2025-03-31 13:47

from django.db import migrations
from django.db.migrations.exceptions import IrreversibleError


def create_ranks(apps, schema_editor):
    from utils.enums import Ranks
    Rank = apps.get_model('game', 'Rank')

    mmr = 0
    for r in Ranks:
        try:
            if not Rank.objects.filter(name=r.name).exists():
                Rank.objects.create(name=r.name, mmr_min=mmr + 1, mmr_max=mmr + 100)
                mmr += 100
        except Exception as e:
            raise IrreversibleError(f'Failed to populate rank table: {e}')


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(create_ranks)
    ]
